# Generated by Django 3.0.3 on 2020-07-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='road_serialized',
            field=models.TextField(default=[]),
        ),
    ]
