# Generated by Django 3.0.3 on 2021-02-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210217_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waypoint',
            name='mission',
        ),
        migrations.AddField(
            model_name='mission',
            name='current_waypoints',
            field=models.ManyToManyField(related_name='mission', to='mainapp.Waypoint', verbose_name='Текущий путь'),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='index',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Порядковый номер'),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='status',
            field=models.SmallIntegerField(choices=[(-1, 'История'), (0, 'Не начат'), (1, 'В процессе'), (2, 'Завершен')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='waypoints_history',
            field=models.ManyToManyField(related_name='mission_history', to='mainapp.Waypoint', verbose_name='История'),
        ),
    ]
