# Generated by Django 3.0.3 on 2021-03-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20210301_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='grid_step',
            field=models.FloatField(default=0.001, verbose_name='Шаг решетки (м)'),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время Waypointа'),
        ),
    ]
