# Generated by Django 3.0.3 on 2021-03-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20210303_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='min_slowdown_ratio',
            field=models.FloatField(default=0.01, verbose_name='Минимальный коэффициент замедления при повороте'),
        ),
        migrations.AddField(
            model_name='drone',
            name='price_per_cycle',
            field=models.FloatField(default=3, verbose_name='Цена за один полет ($)'),
        ),
        migrations.AddField(
            model_name='drone',
            name='price_per_hour',
            field=models.FloatField(default=0.01, verbose_name='Цена за час ($)'),
        ),
        migrations.AddField(
            model_name='drone',
            name='price_per_kilometer',
            field=models.FloatField(default=0.1, verbose_name='Цена за километр ($)'),
        ),
        migrations.AddField(
            model_name='drone',
            name='slowdown_ratio_per_degree',
            field=models.FloatField(default=0.005, verbose_name='Коэффициент замедление на один градус поворота'),
        ),
        migrations.AlterField(
            model_name='drone',
            name='max_distance_no_load',
            field=models.FloatField(verbose_name='Максимальная дальность полета без доп. нагрузки (км)'),
        ),
        migrations.AlterField(
            model_name='drone',
            name='max_height',
            field=models.FloatField(default=1, verbose_name='Максимальная высота (км)'),
        ),
        migrations.AlterField(
            model_name='drone',
            name='max_load',
            field=models.FloatField(verbose_name='Максимальная нагрузка (кг)'),
        ),
        migrations.AlterField(
            model_name='drone',
            name='max_speed',
            field=models.FloatField(default=15, verbose_name='Максимальная скорость (км/ч)'),
        ),
        migrations.AlterField(
            model_name='drone',
            name='weight',
            field=models.FloatField(verbose_name='Вес дрона (кг)'),
        ),
    ]
