# Generated by Django 3.0.3 on 2024-10-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20210322_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='holes_serialized',
            field=models.TextField(default=[], verbose_name='Препятствия (Serialized)'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='drones',
            field=models.ManyToManyField(blank=True, to='mainapp.Drone', verbose_name='Дроны'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='grid_step',
            field=models.FloatField(default=100, verbose_name='Шаг решетки (м)'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='hourly_price',
            field=models.FloatField(default=10, verbose_name='Цена за один час (оплата пилоту, $)'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='start_price',
            field=models.FloatField(default=3, verbose_name='Цена за один старт (оплата пилоту, $)'),
        ),
    ]
