# Generated by Django 3.0.3 on 2026-03-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20250929_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='holes_serialized',
            field=models.TextField(default='[]', verbose_name='Препятствия (Serialized)'),
        ),
        migrations.AlterField(
            model_name='field',
            name='road_serialized',
            field=models.TextField(default='[]'),
        ),
    ]
