# Generated by Django 3.0.3 on 2026-03-27 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0014_auto_20260313_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('grid_step', models.FloatField(default=100, verbose_name='Шаг решетки (м)')),
                ('start_price', models.FloatField(default=3, verbose_name='Цена за один старт ($)')),
                ('hourly_price', models.FloatField(default=10, verbose_name='Цена за один час ($)')),
                ('truck_speed_kmh', models.FloatField(default=40, verbose_name='Скорость машины (км/ч)')),
                ('drones', models.ManyToManyField(blank=True, to='mainapp.Drone', verbose_name='Дроны')),
            ],
            options={
                'verbose_name': 'Кампания',
                'verbose_name_plural': 'Кампании',
            },
        ),
        migrations.CreateModel(
            name='CampaignField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_order', models.PositiveIntegerField(default=0, verbose_name='Порядок по умолчанию')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_fields', to='mainapp.Campaign')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Field')),
            ],
            options={
                'verbose_name': 'Поле кампании',
                'verbose_name_plural': 'Поля кампании',
                'ordering': ['default_order'],
                'unique_together': {('campaign', 'field')},
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='fields',
            field=models.ManyToManyField(through='mainapp.CampaignField', to='mainapp.Field', verbose_name='Поля'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_campaign_name_per_owner'),
        ),
    ]
