# Generated by Django 3.0.3 on 2026-06-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20260327_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='agroscope_meta_serialized',
            field=models.TextField(blank=True, default='', verbose_name='AgroScope метаданные (Serialized)'),
        ),
    ]
